name: Build and Push Docker Image to GCR

on:
  push:
    branches:
      - devops/chathurinda/add-gh-workflow-to-publish-image

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GCR
        uses: docker/login-action@v3
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: Build & Push Docker image
        run: |
          docker build -t gcr.io/vorvan/h2oai/haic-telemetry-exporter .
          docker push gcr.io/vorvan/h2oai/haic-telemetry-exporter:latest
